### ISSUE TITLE
Using BERT with MeTaL

### ISSUE THREAD

**Issue by Peter-UCL** [HazyResearch/metal#178] opened 2019-05-01 16:10 UTC
Are there any plans to release a tutorial of using BERT with MeTaL?
Thanks!

**Comment by bhancock8** [comment] 2019-05-02 04:38
Yes! There are plans. (They've been slowed by other paper deadlines and graduation timelines). The place where we've used BERT with MeTaL internally is with the MMTL package that was just released in v0.5.0. In principle it's quite simple: you just pass in a pretrained BERT module as the input module for one or more of the tasks in your network, and have the data in your Payload include multiple fields (e.g., `tokens` and `segments`, where `tokens` are the wordpiece IDs and `segments` are the assignments to the first or second sentence for multi-sentence inputs). Expect a BERT tutorial in v0.5.1, which will hopefully come out sometime in the next 4-6 weeks.

**Comment by Peter-UCL** [comment] 2019-05-02 17:12
Excellent, thanks.

My progress so far has been refitting the MMTL tutorial for text analysis. I have tried to make the below code as simple as possible (eschewing train, dev, test splits etc.) so that I can just confirm the basics of using BERT with MeTaL.

I started by making a dummy dataset like so:

```
MAX_SEQ_LENGTH = 20

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

dummy_data = [{"Question": "Are you going to the show?", "Answer": "Of course", "Going": True},
{"Question": "Will you be attending this evening?", "Answer": "Unfortunately not", "Going": False},
{"Question": "Are you missing the performance tonight?", "Answer": "Not at all", "Going": True}]

dummy_data = dummy_data * 100

def get_BERT_input_for_example(datum):
    
    # We tokenize our initial data
    tokens_a = tokenizer.tokenize(datum["Question"])
    tokens_b = tokenizer.tokenize(datum["Answer"])
    label = 1 if datum["Going"] else 0

    # We create our input token string by adding BERT's necessary classification and separation tokens
    # We also create the segment id list which is 0 for the first sentence, and 1 for the second sentence
    tokens = ["[CLS]"] + tokens_a + ["[SEP]"]
    segment_ids = [0] * len(tokens)

    tokens += tokens_b + ["[SEP]"]
    segment_ids += [1] * (len(tokens_b) + 1)

    input_ids = tokenizer.convert_tokens_to_ids(tokens)

    # We only attend to the inputted tokens, not the padding tokens
    input_mask = [1] * len(input_ids)

    # Zero-pad up to the sequence length.
    padding = [0] * (MAX_SEQ_LENGTH - len(input_ids))

    input_ids += padding
    input_mask += padding
    segment_ids += padding
    
    return (input_ids, input_mask, segment_ids, label)

tokenized_inputs = list(map(get_BERT_input_for_example, dummy_data))

all_input_ids = torch.tensor([tokenized_input[0] for tokenized_input in tokenized_inputs], dtype=torch.long)
all_input_mask = torch.tensor([tokenized_input[1] for tokenized_input in tokenized_inputs], dtype=torch.long)
all_segment_ids = torch.tensor([tokenized_input[2] for tokenized_input in tokenized_inputs], dtype=torch.long)
all_label_ids = torch.tensor([tokenized_input[3] for tokenized_input in tokenized_inputs], dtype=torch.long)
```

The above code creates token IDs, segment IDs, input masks and labels for each observation, and puts these into a torch tensor.

I make these into my Xs and Ys for this task.
```
X0 = {"tokens": all_input_ids, "segments": all_segment_ids, "input_mask": all_input_mask}

Y0 = all_label_ids
```

Next, I created one task, which is designed to train with this data using the BERT model:
```
input_module = BertModel.from_pretrained('bert-base-uncased')

task0 = ClassificationTask(
    name="GoingTask", 
    input_module=input_module, 
    head_module=torch.nn.Linear(4, 2)
)
```

I then define the payload, tasks list and model like so:
```
from metal.mmtl import MetalModel

tasks = [task0]
model = MetalModel(tasks, verbose=False)

payloads = [Payload.from_tensors(payload_name, X0, Y0, "GoingTask", "train", batch_size=32)]
```

I then set the trainer:
```
from metal.mmtl.trainer import MultitaskTrainer

trainer = MultitaskTrainer()
```

And finally, I train:
```
scores = trainer.train_model(
    model, 
    payloads, 
    n_epochs=2, 
    log_every=2,
    lr=0.02,
    progress_bar=False,
)
```

Firstly, it outputs:
```
Beginning train loop.
Expecting approximately 320 examples total and 10 batches per epoch from 1 payload(s) in the train split.
```
Before spitting out an error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-39-590da8c977f3> in <module>
      5     log_every=2,
      6     lr=0.02,
----> 7     progress_bar=False,
      8 )

~\Anaconda3\lib\site-packages\metal\mmtl\trainer.py in train_model(self, model, payloads, **kwargs)
    222                 # Counts stores the number of examples in each batch with labels by task
    223                 loss_dict, count_dict = model.calculate_loss(
--> 224                     *batch, payload_name, labels_to_tasks
    225                 )
    226 

~\Anaconda3\lib\site-packages\metal\mmtl\metal_model.py in calculate_loss(self, X, Ys, payload_name, labels_to_tasks)
    129         """
    130         task_names = set(labels_to_tasks.values())
--> 131         outputs = self.forward(X, task_names)
    132         loss_dict = {}  # Stores the loss by task
    133         count_dict = {}  # Stores the number of active examples by task

~\Anaconda3\lib\site-packages\metal\mmtl\metal_model.py in forward(self, X, task_names)
    105             input_module = self.input_modules[task_name].module
    106             if input_module not in outputs:
--> 107                 output = input_module(input)
    108                 outputs[input_module] = output
    109 

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~\Anaconda3\lib\site-packages\metal\mmtl\modules.py in forward(self, X)
     18         # passed in so that cached outputs from intermediate modules aren't mutated
     19         X_out = {k: v for k, v in X.items()}
---> 20         X_out["data"] = self.module(X["data"])
     21         return X_out

KeyError: 'data'
```

When I set X0 to be:
```
from torch.utils.data import (DataLoader, RandomSampler, SequentialSampler, TensorDataset)
X0 = TensorDataset(all_input_ids, all_input_mask, all_segment_ids)
```
I get the following error instead:
```
.
.
.
~\Anaconda3\lib\site-packages\metal\mmtl\modules.py in forward(self, X)
     18         # passed in so that cached outputs from intermediate modules aren't mutated
     19         X_out = {k: v for k, v in X.items()}
---> 20         X_out["data"] = self.module(X["data"])
     21         return X_out

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

~\Anaconda3\lib\site-packages\pytorch_pretrained_bert\modeling.py in forward(self, input_ids, token_type_ids, attention_mask, output_all_encoded_layers)
    709     def forward(self, input_ids, token_type_ids=None, attention_mask=None, output_all_encoded_layers=True):
    710         if attention_mask is None:
--> 711             attention_mask = torch.ones_like(input_ids)
    712         if token_type_ids is None:
    713             token_type_ids = torch.zeros_like(input_ids)

TypeError: ones_like() received an invalid combination of arguments - got (list), but expected one of:
 * (Tensor input, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Tensor input, bool requires_grad)
```

I have also tried to simply do `X0 = {"data": X0}`, but that gives me a `'tqdm_notebook' object has no attribute 'sp'` error.

I get that the problem is something to do with how I am packaging my data, but I cannot reckon what the correct way to do it is.

Anyway, I appreciate the software, thanks.

**Comment by HamidShojanazeri** [comment] 2019-06-06 18:57
Thanks a lot for the awesome work on Metal MMTL, I am very interested in using it for NLP tasks and specifically using BERT as the shared model. I was wondering if there is an update on BERT Metal tutorial. 
Thank you very much!

**Comment by bhancock8** [comment] 2019-07-02 07:04
Hi @HamidShojanazeri, great question! As it turns out, we're currently undergoing a big merge combining the best parts of Snorkel, Snorkel MeTaL, the mmtl package, TANDA, and some of our other repos, and massively cleaning/updating every part of it as we go. It's going to be awesome! That release is coming out on the main snorkel repo at the end of this month, along with tutorials showing how to use pre-trained modules in your networks (such as a pretrained BERT network). In the meantime though, we did recently release the code that we used to get SOTA on the SuperGLUE benchmark, and you can find that here: https://github.com/HazyResearch/snorkel-superglue. It's less documented, since it's application code rather than the core that we're focusing on right now, but you could use that as a starting point for your own problem if you'd like. Best of luck!

**Comment by bhancock8** [comment] 2019-07-02 07:10
@Peter-UCL I suspect that the problem is that for the MetalModule to function properly, all of the modules that pass it need to accept and return dictionaries (both for the attributes of your data, and for your labels). And the BERT module on its own just returns a tuple, I believe. So you may need to put a thin wrapper around the module to convert its outputs into the right form (from a tuple into a dict) so that it plays nicely with the rest of the network.

**Comment by vincentschen** [comment] 2019-08-15 20:54
Hi @Peter-UCL — thanks again for the interest here! Closing this issue; please feel free to raise any additional ones in our https://github.com/HazyResearch/snorkel-superglue if you have any follow-up questions! Also, don't hesitate to post discussions on our [forum](https://spectrum.chat/snorkel?tab=posts) about integrations, models, tutorial, etc. that you've tried/would like to see in Snorkel!

**Closed by vincentschen** 2019-08-15 20:54 UTC
