### ISSUE TITLE
Instability of label model

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/metal#36] opened 2018-09-01 17:56 UTC
Hi,

Sorry for bothering you again.

I found some weird behavior in the label model where I run the label model twice with the same data and I got the totally different result. Here you can find a snapshot of my code.

![screen shot 2018-09-01 at 10 54 35 am](https://user-images.githubusercontent.com/5580008/44948599-7b1df400-add5-11e8-8334-1e09becd9edb.png)

Data: basics_tutorial.pkl
Code: snorkel-metal 0.1.1 

Please let me know if I am doing something wrong.

Thanks,
Sen

**Comment by chrismre** [comment] 2018-09-01 18:07
This a great issue, Sen! 

A naive guess is that the symmetry isn't broken consistently, there is a always a symmetry e.g., p -> 1-p for labeling function accuracies. This is where the theory elects a particular winner @ajratner @fredsala any thoughts here?

Can you add in the LF function accuracies to confirm or refute that guess? Thanks!

**Comment by ajratner** [comment] 2018-09-01 18:08
Hi Sen,

Thanks for posting- keep them coming! At the end of the training we learn
the model up to symmetry- and then break symmetry based on the fact the LFs
are non-adversarial. But apparently this isn’t happening correctly here!
Either way it’s an easy thing to resolve- I will do so a little bit later
today

Thanks,
Alex

**Comment by ajratner** [comment] 2018-09-01 18:14
@SenWu @chrismre Yes this is definitely what's going on- in transit now but then I'll resolve in a bit! First try is just by changing the defaults to use centered L2, which is not currently on by default, in addition to initialization to resolve this symmetry- should take care of it

**Comment by ajratner** [comment] 2018-09-01 23:31
Hi @SenWu I'm having a hard time reproducing the behavior you have above- have you pulled the latest version of master?  Any other differences that might explain this?

I still think this must be a symmetry-breaking issue, just confused that I can't replicate.  We can talk on slack abt too!

**Comment by ajratner** [comment] 2018-09-01 23:35
Looks like this is fixed on master, need to propagate to the pip installable version

**Comment by lukehsiao** [comment] 2018-09-02 07:48
If you have the latest code on master and are tagging releases to pypi, I'd highly recommend incrementing the version number in master after a release (e.g. to v0.1.6). This avoids the issue where if a user installs from pypi, they get v0.1.5, and if a user installs from GitHub, they get v0.1.5, but they are not actually the same versions.

**Comment by ajratner** [comment] 2018-09-07 15:38
@lukehsiao thanks, will do!

@SenWu note I added in centered L2 reg (see updated Basics tutorial) which might also generally be useful for these types of symmetry-breaking issues, if they come up

Also, unless any strong objections, I'm going to start closing issues when they are fixed **on master**; then I will increase the frequency of pushing new versions to pip.  Happy to hear pushback on this... but since I still view this repo as in 'dev-heavy mode' (research!!), I think this will be cleaner

**Closed by ajratner** 2018-09-07 15:38 UTC
Labels: bug
